# Site settings
title: Starignus World
description: A start stuff with consciousness 
keywords: Data Science, Physics, Feminism, Skepticism, Science
author: Ariadna Blanca Romero
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
